# Generated by Django 6.0.7 on 2026-07-14 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=150, verbose_name='Modelo')),
                ('versao', models.CharField(help_text='Ex: 1.0 Turbo Flex Automático', max_length=150, verbose_name='Versão')),
                ('ano_fabricacao', models.PositiveIntegerField(verbose_name='Ano de Fabricação')),
                ('ano_modelo', models.PositiveIntegerField(verbose_name='Ano do Modelo')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço (R$)')),
                ('quilometragem', models.PositiveIntegerField(default=0, verbose_name='Quilometragem (Km)')),
                ('cor', models.CharField(max_length=50, verbose_name='Cor')),
                ('portas', models.IntegerField(choices=[(2, '2 Portas'), (4, '4 Portas')], default=4, verbose_name='Quantidade de Portas')),
                ('estado', models.CharField(choices=[('NOVO', 'Novo (Zero Km)'), ('SEMI', 'Seminovo'), ('USADO', 'Usado')], default='USADO', max_length=5, verbose_name='Estado de Conservação')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição/Opcionais')),
                ('imagem_principal', models.ImageField(blank=True, null=True, upload_to='carros/', verbose_name='Foto Principal')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='catalogo.marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
